### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by KaptainCS3**
fetch joke and create joke functionality implemented
review looking forward to merging this PR

### CODE REVIEW

**Review by Formasitchijoh — CHANGES_REQUESTED** [review]
I don't know why you have more than the usual categories in your select drop down if they are for knowing the value of the option selected you should uses a state to hold them and them pass the onchangehandler to select so that the new option gets selected everytime you select an option

**Review by Formasitchijoh — APPROVED** [review]
using object at times  might be reduntdnt  in class base implementation

**Review by Formasitchijoh — APPROVED** [review]
I know commit messages are hard to compose but try to compose something

**Comment by KaptainCS3** [comment]
I will change the category to match that of the API but I lifted the state so that it can be accessible everywhere in my app.

**Pull request merged**
